
application: coastal-valuation
version: v1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "latest" 
- name: numpy
  version: 1.6.1

handlers:
- url: /.*
  script: api.handlers
